<?php

/*
 * @file 
 * User interface tweaks and other modifications for the Stanford Sites platform
 */

/*
 * Implementation of hook_theme_registry_alter().
 */
function stanford_core_theme_registry_alter(&$theme_registry) {
  $theme_registry['box']['function'] = 'stanford_core_box'; 
  $theme_registry['box']['path'] = drupal_get_path('module', 'stanford_core');
}

/*
 * Override of search#noresults.
 * See hook_help() in search.module.
 */
function stanford_core_box($title, $content, $region = 'main') {
  if ($title == 'Your search yielded no results') {
    $content = '<ul>';
    $content .= '<li>'. t('Check if your spelling is correct.') .'</li>';
    $content .= '<li>'. t('Simplify your search by using fewer words.') .'</li>';
    $content .= '<li>'. t('Remove quotes around phrases to match each word individually: %stanfordquote will match less than %stanfordnoquote.', array('%stanfordquote' => '"stanford university"', '%stanfordnoquote' => 'stanford university')) .'</li>';
    $content .= '<li>'. t('Consider loosening your query with <em>OR</em>: <em>stanford university</em> will match less than <em>stanford OR university</em>.') .'</li>';
    $content .= '</ul>';
  }
  $output = '<h2 class="title">'. $title .'</h2><div>'. $content .'</div>';
  return $output;
}

/*
 * Implementation of hook_menu().
 */
function stanford_core_menu() {
//  $items = array();
  $items['stanford-front-page-default'] = array(
    'title' => 'Welcome to Your Stanford Sites Website',
    'access arguments' => array('access content'),
    'page callback' => 'stanford_core_frontpage',
    'type' => MENU_CALLBACK,
  );
  return $items;
}

/*
 * Fix spell check as you type (scayt) autostart behavior.
 * See http://drupal.org/node/817894 for reference.
 */
function stanford_core_wysiwyg_editor_settings_alter(&$settings, $context) {
  if ($context['profile']->editor == 'ckeditor') {
    $settings['scayt_autoStartup'] = FALSE;
  }
}

/*
 * Return content for default front page.
 */
function stanford_core_frontpage() {
  $output = 'Here are the steps to take.';
  return $output;
}

